name: Create deployment from user's input 

# Triggers the workflow on api call
on:
  repository_dispatch:
    types: [json]
    
env:
  JSON: ${{ github.event.client_payload.json_file }}   


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: Checkout
       uses: actions/checkout@v2
       
     - name: Update CloudFlare DNS with Cluster IP 
       run: |-
         echo "JSON"
